---

# Initialize the Language
language: python

# Declare Docker Service to be used in the build
services: docker

# Environments variables for test
env:

    # Global
    global:
        - ROLE_NAME: java
        - AUTHOR: jetune
    matrix:
        - MOLECULE_DISTRO: centos7
        - MOLECULE_DISTRO: ubuntu18

# Installation actions
install:

    # Install Test tools
    - pip install molecule docker flake8

    # Uninstall testinfra 1.19.0
    - pip uninstall -y testinfra==1.19.0

    # Install testinfra 3.0.5
    - pip install testinfra==3.0.5

# Test scripts
script:

    # Run Tests
    - molecule test

# Script to execute after the builds
after_script:

    # Move to parent directory
    - cd ../

    # rename folder
    - mv ansible-role-$ROLE_NAME $AUTHOR.$ROLE_NAME

    # Go back to directory
    - cd $AUTHOR.$ROLE_NAME

# Norifications
notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
