---

- name: Download Open JDK ( URL = {{ url }}, DEST = {{ downloaded_file }}, CHECK = {{ checksum }})
  get_url:
   url: "{{ url }}"
   dest: "{{ downloaded_file }}"
   checksum: "{{ checksum }}"
  when:
   - jdk_implementation == "OPENJDK"
   - not jdk_from_repo
