---

- name: Download Open JDK (7ux or 8ux)
  get_url:
   url: "https://download.java.net/openjdk/jdk{{ item.v_major }}u{{ item.v_minor }}/ri/openjdk-{{ item.v_major }}u{{ item.v_minor }}-b{{ item.build }}-{{ item.os }}-{{ item.arch }}-{{ item.date }}.tar.gz"
   dest: "/tmp/openjdk-{{ item.v_major }}{{ item.v_minor }}.tar.gz"
   checksum: "{{ item.checksum }}"
  with_items: "{{ __java_packages }}"
  when:
   - item.v_major|int == 8 or item.v_major|int == 7
   - item.implementation is defined and item.implementation == "OPENJDK"
   - item.from_repo is not defined or not item.from_repo

- name: Download Open JDK (9.x.y and 10)
  get_url:
   url: "https://download.java.net/java/GA/jdk{{ item.v_major }}/{{ item.v_major }}{{ item.v_minor }}/binaries/openjdk-{{ item.v_major }}{{ item.v_minor }}_{{ item.os }}-{{ item.arch }}_bin.tar.gz"
   dest: "/tmp/openjdk-{{ item.v_major }}{{ item.v_minor }}.tar.gz"
   checksum: "{{ item.checksum }}"
  with_items: "{{ __java_packages }}"
  when:
   - item.v_major|int == 9 or (item.v_major|int == 10 and not item.v_minor)
   - item.implementation is defined and item.implementation == "OPENJDK"
   - item.from_repo is not defined or not item.from_repo

- name: Download Open JDK (10.x.y)
  get_url:
   url: "https://download.java.net/java/GA/jdk{{ item.v_major }}/{{ item.v_major }}{{ item.v_minor }}/{{ item.hash }}/{{ item.build }}/openjdk-{{ item.v_major }}{{ item.v_minor }}_{{ item.os }}-{{ item.arch }}_bin.tar.gz"
   dest: "/tmp/openjdk-{{ item.v_major }}{{ item.v_minor }}.tar.gz"
   checksum: "{{ item.checksum }}"
  with_items: "{{ __java_packages }}"
  when:
   - item.v_major|int == 10 and item.v_minor
   - item.implementation is defined and item.implementation == "OPENJDK"
   - item.from_repo is not defined or not item.from_repo

- name: Download Open JDK (11)
  get_url:
   url: "https://download.java.net/java/ga/jdk{{ item.v_major }}/openjdk-{{ item.v_major }}_{{ item.os }}-{{ item.arch }}_bin.tar.gz"
   dest: "/tmp/openjdk-{{ item.v_major }}{{ item.v_minor }}.tar.gz"
   checksum: "{{ item.checksum }}"
  with_items: "{{ __java_packages }}"
  when:
   - item.v_major|int == 11 and not item.v_minor
   - item.implementation is defined and item.implementation == "OPENJDK"
   - item.from_repo is not defined or not item.from_repo

- name: Download Open JDK (11.x.y, 12.x.y)
  get_url:
   url: "https://download.java.net/java/GA/jdk{{ item.v_major }}/{{ item.build }}/GPL/openjdk-{{ item.v_major }}{{ item.v_minor }}_{{ item.os }}-{{ item.arch }}_bin.tar.gz"
   dest: "/tmp/openjdk-{{ item.v_major }}{{ item.v_minor }}.tar.gz"
   checksum: "{{ item.checksum }}"
  with_items: "{{ __java_packages }}"
  when:
   - (item.v_major|int == 11 and item.v_minor) or item.v_major|int == 12
   - item.implementation is defined and item.implementation == "OPENJDK"
   - item.from_repo is not defined or not item.from_repo
