---

- name: ({{ ansible_distribution }}) Download Open JDK ( URL = {{ url }}, DEST = {{ downloaded_file }})
  get_url:
   url: "{{ url }}"
   dest: "{{ downloaded_file }}"
   checksum: "{{ checksum }}"
  when:
   - jdk_implementation == "OPENJDK"
   - not jdk_from_repo
