---

- name: [{{ ansible_distribution }}] Add Debian based requested repositories if exists
  apt_repository:
   repo: "{{ item.repo }}"
   state: present
   update_cache: true
  with_items: "{{ __repositories }}"
  when:
   - item.os is defined
   - __repositories is defined
   - item.os == ansible_os_family or item.os == ansible_distribution
   - ansible_os_family == "Debian"
   - item.v_major == ansible_distribution_major_version

- name: [{{ ansible_distribution }}] Add RedHat based requested repositories if exists
  yum_repository:
   name: "{{ item.name }}"
   baseurl: "{{ item.repo }}"
   enabled: "yes"
   enablegroups: "yes"
   keepalive: "{{ item.keepalive | default('yes') }}"
   keepcache: "{{ item.keepcache | default('1') }}"
   metadata_expire: "{{ item.metadata_expire | default('21600') }}"
   password: "{{ item.password | default('') }}"
   username: "{{ item.username | default('') }}"
   timeout: "{{ item.timeout | default('30') }}"
   sslverify: "{{ item.sslverify | default('yes') }}"
   sslclientkey: "{{ item.sslclientkey | default('') }}"
   sslclientcert: "{{ item.sslclientcert | default('') }}"
   reposdir: "{{ item.reposdir | default('/etc/yum.repos.d') }}"
   state: present
  with_items: "{{ __repositories }}"
  when:
   - item.os is defined
   - __repositories is defined
   - item.os == ansible_os_family or item.os == ansible_distribution
   - ansible_os_family == "RedHat"
   - item.v_major == ansible_distribution_major_version

- name: [{{ ansible_distribution }}] Check Java required parameters (v_major, os, arch, checksum")
  fail:
   msg: "Vérifier les paramètres obligatoires : (v_major, os, arch, checksum)"
  when: >
   v_major is not defined or
   os is not defined or
   os is not defined or
   arch is not defined or
   checksum is not defined

- name: [{{ ansible_distribution }}] Check Java required parameter for Java 7 or 8
  fail:
   msg: "Vérifier les paramètres obligatoire des version 7 et 8 : date"
  when:
   - v_major|int == 8 or v_major|int == 7
   - date is not defined

- name: [{{ ansible_distribution }}] Check Java required parameter for Java 10
  fail:
   msg: "Vérifier les paramètres obligatoire de la version 10 : hash"
  when:
   - v_major|int == 10
   - hash is not defined

- name: Define installation directories for Debian family
  set_fact:
   install_dir: "/usr/lib/jvm/java-{{ v_major }}.{{ v_minor }}-openjdk"
   downloaded_file: "/tmp/openjdk-{{ v_major }}.{{ v_minor }}.tar.gz"
   jdk_implementation: "{{ implementation | default('OPENJDK') }}"
   jdk_default: "{{ is_default | default(true) }}"
   jdk_from_repo: "{{ from_repo | default(false) }}"
   alternatives:
    - 'java'
    - 'javac'
    - 'javadoc'
    - 'jar'
    - 'jarsigner'
    - 'javap'
    - 'jcmd'
    - 'jconsole'
    - 'keytool'
    - 'rmiregistry'
    - 'rmic'
    - 'rmid'

- name: [{{ ansible_distribution }}] Define Download URL for version 7x or 8x
  set_fact:
   url: "https://download.java.net/openjdk/jdk{{ v_major }}u{{ v_minor }}/ri/openjdk-\
   {{ v_major }}u{{ v_minor }}-b{{ build }}-{{ os }}-{{ arch }}-{{ date }}.tar.gz"
  when:
   - v_major|int == 8 or v_major|int == 7

- name: [{{ ansible_distribution }}] Define Download URL for version 9x
  set_fact:
   url: "https://download.java.net/java/GA/jdk{{ v_major }}/{{ v_major }}.{{ v_minor }}\
   /binaries/openjdk-{{ v_major }}.{{ v_minor }}_{{ os }}-{{ arch }}_bin.tar.gz"
  when:
   - v_major|int == 9

- name: [{{ ansible_distribution }}] Define Download URL for version 10x
  set_fact:
   url: "https://download.java.net/java/GA/jdk{{ v_major }}/{{ v_major }}.{{ v_minor }}\
   /{{ hash }}/{{ build }}/openjdk-{{ v_major }}.{{ v_minor }}_{{ os }}-{{ arch }}_bin.tar.gz"
  when:
   - v_major|int == 10

- name: [{{ ansible_distribution }}] Define Download URL for version 11x et 12x
  set_fact:
   url: "https://download.java.net/java/GA/jdk{{ v_major }}/{{ build }}/GPL/openjdk-\
   {{ v_major }}.{{ v_minor }}_{{ os }}-{{ arch }}_bin.tar.gz"
  when:
   - v_major|int == 11 or v_major|int == 12
