---

- name: {{ ansible_distribution }} - Install RedHat Based OpenJDK from Repo
  yum:
   name: "java-1.{{ v_major }}.0-openjdk"
   state: present
  when:
   - ansible_os_family == "RedHat"
   - jdk_implementation == "OPENJDK"
   - jdk_from_repo

- name: {{ ansible_distribution }} - Install Debian Based OpenJDK from Repo
  apt:
   name: "openjdk-{{ v_major }}-jdk"
   state: present
  when:
   - ansible_os_family == "Debian"
   - jdk_implementation == "OPENJDK"
   - jdk_from_repo

- name: {{ ansible_distribution }} - Create Downloaded archive installation directories
  file:
   path: "{{ install_dir }}"
   state: directory
  when:
   - jdk_implementation == "OPENJDK"
   - not jdk_from_repo

- name: {{ ansible_distribution }} - Unarchive Downloaded Open JDK archives
  unarchive:
   src: "{{ downloaded_file }}"
   dest: "{{ install_dir }}"
   creates: "{{ install_dir }}/bin/java"
   remote_src: true
   extra_opts:
    - --strip-components=1
  when:
   - jdk_implementation == "OPENJDK"
   - not jdk_from_repo

- name: {{ ansible_distribution }} - Set the Java Alternatives (Default JDK = {{ jdk_default }})
  alternatives:
   name: "{{ item }}"
   link: "/usr/bin/{{ item }}"
   path: "{{ install_dir }}/bin/{{ item }}"
   priority: "{{ alternative_priority }}"
  with_items: "{{ alternatives }}"

- name: {{ ansible_distribution }} - Make sure /etc/profile.d/ directory exists
  file:
   path: "/etc/profile.d/"
   mode: 0755
   state: directory
  when:
   - jdk_default

- name: {{ ansible_distribution }} - Set the JAVA_HOME (Default JDK = {{ jdk_default }})
  template:
   src: "templates/java_home.sh.j2"
   dest: "/etc/profile.d/java_home.sh"
   mode: a+x
  when:
   - jdk_default
