---

- name: Install RedHat Based OpenJDK from Repo
  yum:
   name: "java-1.{{ item.v_major }}.0-openjdk"
   state: present
  with_items: "{{ __java_packages }}"
  when:
   - ansible_os_family == "RedHat"
   - item.implementation is defined and item.implementation == "OPENJDK"
   - item.from_repo

- name: Install Debian Based OpenJDK from Repo
  apt:
   name: "openjdk-{{ item.v_major }}-jdk"
   state: present
  with_items: "{{ __java_packages }}"
  when:
   - ansible_os_family == "Debian"
   - item.implementation is defined and item.implementation == "OPENJDK"
   - item.from_repo

- name: Create Downloaded archive installation directories
  file:
   path: "{{ install_dir | replace('$v_major', item.v_major) | replace('$v_minor', item.v_minor) }}"
   state: directory
  with_items: "{{ __java_packages }}"
  when:
   - item.implementation is defined and item.implementation == "OPENJDK"
   - not item.from_repo

- name: Unarchive Downloaded Open JDK archives
  unarchive:
   src: "/tmp/openjdk-{{ item.v_major }}{{ item.v_minor }}.tar.gz"
   dest: "{{ install_dir | replace('$v_major', item.v_major) | replace('$v_minor', item.v_minor) }}"
   creates: "{{ install_dir | replace('$v_major', item.v_major) | replace('$v_minor', item.v_minor) }}\
   /bin/java"
   remote_src: true
   extra_opts:
    - --strip-components=1
  with_items: "{{ __java_packages }}"
  when:
   - item.implementation is defined and item.implementation == "OPENJDK"
   - not item.from_repo

- name: Set the Java Alternatives
  alternatives:
   name: "{{ item[1] }}"
   link: "/usr/bin/{{ item[1] }}"
   path: "{{ install_dir | replace('$v_major', item[0].v_major) | replace('$v_minor', item[0].v_minor) }}\
   /bin/{{ item[1] }}"
   priority: "{{ item[0].alternative_priority }}"
  with_nested:
   - "{{ __java_packages }}"
   - "{{ alternatives }}"
  when:
   - item[0].implementation is defined and item[0].implementation == "OPENJDK"
   - not item[0].from_repo

- name: Make sure /etc/profile.d/ directory exists
  file:
   path: "/etc/profile.d/"
   mode: 0755
   state: directory

- name: Set the JAVA_HOME
  template:
   src: "templates/java_home.sh.j2"
   dest: "/etc/profile.d/java_home.sh"
   mode: a+x
  with_items: "{{ __java_packages }}"
  when:
   - item.java_home
   - not item.from_repo
