---
dependency:
    name: galaxy
driver:
    name: docker
lint: |
    yamllint .
platforms:
    - name: ${MOLECULE_DISTRO:-centos7}
      image: "kubecloudsas/docker-ansible-test:${MOLECULE_DISTRO:-centos7}"
      command: ${MOLECULE_DOCKER_COMMAND:-""}
      volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
      privileged: true
      pre_build_image: true

provisioner:
    name: ansible
    lint:
        name: ansible-lint
        options:
            force-color: true
    playbooks:
        converge: ${MOLECULE_PLAYBOOK:-playbook.yml}

scenario:
    name: openjdk11
    test_sequence:
        - lint
        - dependency
        - syntax
        - create
        - prepare
        - converge
        - idempotence
        - side_effect
        - verify
        - cleanup
        - destroy
verifier:
    name: testinfra
    lint:
        name: flake8
