---
- name: Converge OpenJDK 7
  hosts: all
  roles:
   - role: ansible-role-java
     vars:
      from_repo: false
      implementation: OPENJDK
      v_major: 7
      v_minor: 75
      build: 13
      os: linux
      arch: x64
      date: 18_dec_2014
      checksum: md5:538acd35c6cf6977fa19d21ab2c17b0a
      alternative_priority: 300
      cacerts_override: true
      cacerts_path: "jks/cacerts"
      is_default: true
